import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { MainLayout } from '../components/layout/MainLayout';
import { LogInIcon, UploadIcon, BotIcon, FileTextIcon, SettingsIcon, AlertCircleIcon, MessageCircleIcon, ArrowLeftIcon, ChevronDownIcon, ChevronRightIcon } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
export function HelpPage() {
  const navigate = useNavigate();
  const [expandedSection, setExpandedSection] = useState<number | null>(0);
  const helpSections = [{
    icon: <LogInIcon size={32} className="text-blue-600" />,
    title: 'How to Login',
    description: 'Enter your email and password to access your DeepLex account. If you forgot your password, click "Forgot Password?" to reset it.',
    steps: [{
      step: 'Navigate to the login page',
      detail: 'Open your browser and go to the DeepLex login page'
    }, {
      step: 'Enter your registered email address',
      detail: 'Type the email you used when creating your account'
    }, {
      step: 'Enter your password',
      detail: 'Input your secure password (minimum 8 characters)'
    }, {
      step: 'Click "Sign in" button',
      detail: 'Press the blue "Sign in" button to access your dashboard'
    }, {
      step: "If credentials are incorrect, you'll see an error message",
      detail: 'Double-check your email and password. Use "Forgot Password?" if needed'
    }]
  }, {
    icon: <UploadIcon size={32} className="text-green-600" />,
    title: 'How to Upload a Document',
    description: 'Upload legal documents in PDF, DOCX, or TXT format for AI-powered analysis.',
    steps: [{
      step: 'Click "Upload Document" from the dashboard',
      detail: 'Find the bright blue "Upload Document" button in the top action bar'
    }, {
      step: 'Drag and drop your file or click "Select Files"',
      detail: 'Either drag your document into the upload area or browse your computer'
    }, {
      step: 'Review file metadata and preview',
      detail: "Check file name, size, and upload date. Ensure it's the correct document"
    }, {
      step: 'Select privacy settings if needed',
      detail: 'Choose if the document should be private, add watermark, or mark as confidential'
    }, {
      step: 'Click "Continue to Agent Selection"',
      detail: 'Proceed to choose which AI agent will analyze your document'
    }]
  }, {
    icon: <BotIcon size={32} className="text-purple-600" />,
    title: 'How to Choose an Agent',
    description: 'Select the AI agent that best fits your document analysis needs.',
    steps: [{
      step: 'Review the four available agents',
      detail: 'Each agent card shows its purpose, processing time, and capabilities'
    }, {
      step: 'Clause Extraction: Extract and categorize clauses',
      detail: 'Identifies all contract clauses with categories and confidence scores (~2 min)'
    }, {
      step: 'Risk Detection: Identify legal risks and compliance issues',
      detail: 'Scans for potential risks with severity ratings and recommendations (~3 min)'
    }, {
      step: 'Drafting Agent: Generate and improve contract language',
      detail: 'Suggests improvements with original vs. improved text comparisons (~4 min)'
    }, {
      step: 'Summary Agent: Create concise document summaries',
      detail: 'Generates executive summaries with key points and obligations (~1 min)'
    }, {
      step: 'Click on your chosen agent to proceed',
      detail: 'The agent will start processing immediately. You can track progress in real-time'
    }]
  }, {
    icon: <FileTextIcon size={32} className="text-yellow-600" />,
    title: 'How to View Reports',
    description: 'Access detailed analysis reports generated by AI agents.',
    steps: [{
      step: 'Navigate to the "Reports" section',
      detail: 'Click "View All Reports" from the dashboard or use the sidebar menu'
    }, {
      step: 'Select the report you want to view',
      detail: 'Browse through your reports list. Use filters to find specific reports'
    }, {
      step: 'Review findings, metrics, and recommendations',
      detail: 'Each report shows detailed analysis with confidence scores and insights'
    }, {
      step: 'Download reports in PDF or DOCX format',
      detail: 'Click the "Download" button to save reports to your computer'
    }, {
      step: 'Share reports with team members',
      detail: 'Use the "Share" button to send reports via email or generate a shareable link'
    }]
  }, {
    icon: <SettingsIcon size={32} className="text-blue-600" />,
    title: 'How to Use Settings',
    description: 'Customize your DeepLex experience and manage your account.',
    steps: [{
      step: 'Click "Settings" from the sidebar',
      detail: 'Find the settings icon in the left sidebar navigation menu'
    }, {
      step: 'Update your profile information',
      detail: 'Change your name, email, and role in the Profile tab'
    }, {
      step: 'Change password and security settings',
      detail: 'Update your password and configure two-factor authentication in Security tab'
    }, {
      step: 'Configure AI agent preferences',
      detail: 'Set analysis depth (Quick/Balanced/Thorough), output tone, and confidence threshold'
    }, {
      step: 'Manage notification preferences',
      detail: 'Toggle email, push, and weekly summary notifications on/off'
    }, {
      step: 'Set document retention policies',
      detail: 'Choose how long documents are stored (30 days to forever)'
    }]
  }, {
    icon: <AlertCircleIcon size={32} className="text-red-600" />,
    title: 'Fix Incorrect Credentials',
    description: 'Troubleshoot login issues and reset your password.',
    steps: [{
      step: 'Double-check your email address for typos',
      detail: 'Ensure there are no extra spaces or incorrect characters in your email'
    }, {
      step: 'Ensure Caps Lock is off when entering password',
      detail: 'Passwords are case-sensitive. Check your keyboard settings'
    }, {
      step: 'Click "Forgot Password?" if you can\'t remember',
      detail: 'Located below the password field on the login page'
    }, {
      step: 'Check your email for password reset link',
      detail: 'Look in your inbox and spam folder for an email from DeepLex'
    }, {
      step: 'Contact support if issues persist',
      detail: 'Use the "Contact Support" button in Help & Support for assistance'
    }]
  }];
  const toggleSection = (index: number) => {
    setExpandedSection(expandedSection === index ? null : index);
  };
  return <MainLayout backgroundColor="bg-white">
      <div className="max-w-7xl mx-auto">
        <motion.div initial={{
        opacity: 0,
        y: 20
      }} animate={{
        opacity: 1,
        y: 0
      }} transition={{
        duration: 0.5
      }}>
          {/* Back Button */}
          <button onClick={() => navigate('/dashboard')} className="mb-6 flex items-center text-blue-600 hover:text-blue-700 transition-colors">
            <ArrowLeftIcon size={20} className="mr-2" />
            Back to Dashboard
          </button>

          {/* Header */}
          <div className="mb-10">
            <h1 className="text-4xl font-bold text-gray-900 mb-2">
              Help & Support
            </h1>
            <p className="text-gray-600 text-lg">
              Step-by-step guides to help you navigate and use DeepLex
              effectively
            </p>
          </div>

          {/* Help Sections - Accordion Style */}
          <div className="space-y-4 mb-12">
            {helpSections.map((section, index) => <motion.div key={index} initial={{
            opacity: 0,
            y: 20
          }} animate={{
            opacity: 1,
            y: 0
          }} transition={{
            duration: 0.5,
            delay: index * 0.05
          }} className="bg-white border border-gray-200 rounded-lg shadow-sm overflow-hidden">
                <button onClick={() => toggleSection(index)} className="w-full p-6 flex items-center justify-between hover:bg-gray-50 transition-colors">
                  <div className="flex items-center space-x-4">
                    <div className="p-3 bg-gray-100 rounded-lg">
                      {section.icon}
                    </div>
                    <div className="text-left">
                      <h3 className="text-xl font-semibold text-gray-900 mb-1">
                        {section.title}
                      </h3>
                      <p className="text-gray-600 text-sm">
                        {section.description}
                      </p>
                    </div>
                  </div>
                  <motion.div animate={{
                rotate: expandedSection === index ? 180 : 0
              }} transition={{
                duration: 0.3
              }}>
                    <ChevronDownIcon size={24} className="text-gray-600" />
                  </motion.div>
                </button>

                <AnimatePresence>
                  {expandedSection === index && <motion.div initial={{
                height: 0,
                opacity: 0
              }} animate={{
                height: 'auto',
                opacity: 1
              }} exit={{
                height: 0,
                opacity: 0
              }} transition={{
                duration: 0.3
              }} className="overflow-hidden">
                      <div className="px-6 pb-6 pt-2 border-t border-gray-200">
                        <div className="space-y-4">
                          {section.steps.map((stepItem, stepIndex) => <motion.div key={stepIndex} initial={{
                      opacity: 0,
                      x: -20
                    }} animate={{
                      opacity: 1,
                      x: 0
                    }} transition={{
                      duration: 0.3,
                      delay: stepIndex * 0.05
                    }} className="flex items-start space-x-4 p-4 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors">
                              <div className="flex-shrink-0 w-8 h-8 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-sm font-semibold border border-blue-200">
                                {stepIndex + 1}
                              </div>
                              <div className="flex-1">
                                <p className="text-gray-900 font-medium mb-1">
                                  {stepItem.step}
                                </p>
                                <p className="text-gray-600 text-sm">
                                  {stepItem.detail}
                                </p>
                              </div>
                              <ChevronRightIcon size={20} className="text-gray-300 flex-shrink-0 mt-1" />
                            </motion.div>)}
                        </div>
                      </div>
                    </motion.div>}
                </AnimatePresence>
              </motion.div>)}
          </div>

          {/* Contact Support */}
          <motion.div initial={{
          opacity: 0,
          y: 20
        }} animate={{
          opacity: 1,
          y: 0
        }} transition={{
          duration: 0.5,
          delay: 0.6
        }} className="bg-white border border-gray-200 rounded-lg shadow-sm p-8 text-center">
            <MessageCircleIcon size={48} className="text-blue-600 mx-auto mb-4" />
            <h2 className="text-2xl font-bold text-gray-900 mb-2">
              Still Need Help?
            </h2>
            <p className="text-gray-600 mb-6">
              Our support team is here to assist you with any questions or
              issues.
            </p>
            <div className="flex justify-center space-x-4">
              <button className="flex items-center px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium">
                <MessageCircleIcon size={18} className="mr-2" />
                Contact Support
              </button>
              <button className="flex items-center px-4 py-2 bg-white border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 transition-colors font-medium">
                View Documentation
              </button>
            </div>
          </motion.div>
        </motion.div>
      </div>
    </MainLayout>;
}